### ISSUE TITLE
Add delay to the .desktop file or a retry to the script

### ISSUE THREAD

**Issue by JacekJagosz** [pipipear/VoiceStatus#1]
First, I wanted to thank you so much for this plugin, which works beautifully.
It works really well for me if I start it manually. But the autostart .desktop file isn't working for me, because it takes a few seconds after boot for my setup to connect to the internet. So the script runs and fails before there is internet.
What I did for now is I replaced the `Exec` line with `Exec=bash -c "sleep 5 && ~/go/bin/VoiceServer"`. This is not a clean solution but works for now.
So could you add a delay by default to the autostart file, or maybe a retry if there is no internet connection?

**Comment by pipipear** [comment]
Could you try removing the autostart entry and adding [VoiceServer.service](https://github.com/pipipear/VoiceStatus/blob/main/VoiceServer.service) to `~/.config/systemd/user/`?

**Comment by JacekJagosz** [comment]
At first it failed when I did `systemctl enable ~/.config/systemd/user/VoiceServer.service`:
```
● VoiceServer.service - VoiceServer
     Loaded: loaded (/etc/systemd/system/VoiceServer.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2022-04-27 16:06:09 CEST; 1s ago
    Process: 2416 ExecStart=/root/go/bin/VoiceServer (code=exited, status=203/EXEC)
   Main PID: 2416 (code=exited, status=203/EXEC)
        CPU: 896us
```
But it was my mistake, when I did `systemctl enable --user ~/.config/systemd/user/VoiceServer.service` all is working flawlessly!
So it would be awesome if you added this method to the readme. And thanks once again for such a cool plugin.
