### ISSUE TITLE
Widget not respecting original size and getting taller

### ISSUE THREAD

**Issue by JacekJagosz** [pipipear/VoiceStatus#2]
First, once again thank you for this awesome plugin!
Since the beginning I have been dealing with a bug that annoys me. When I set it to a small size at the beginning, when someone will join a channel it will extend to be higher, to fit that image. It seems to be dependent on resolution of their profile picture too, as depending on which of my friends join it will enlarge to different heights. Also, as long as they are shown on the widget I can't reduce its size, only when they leave.
Could you change the code so that the images will get scaled to fit in the current size of the widget?

**Comment by pipipear** [comment]
I'm not completely sure what was causing this as it happened at random, but after playing with some QML properties it seems https://github.com/pipipear/VoiceStatus/commit/0148440cf01ff7ef8daeee917f001df1b42971d9 fixes it. Please let me know if this issue persists.

**Comment by JacekJagosz** [comment]
It seems to have fixed it! Thank you so much!
